name: Tofu Apply

on:
  push:
    branches: ["main"]
    paths: ["scripts/tofu/live/**/*.tf"]

jobs:
  apply:
    name: "Tofu Apply"
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v45

      - uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.APPLY_ROLE_ARN }}
          role-session-name: apply-${{ github.run_number }}-${{ github.actor }}
          aws-region: us-east-2

      - uses: opentofu/setup-opentofu@v1

      - name: Run Tofu Apply
        id: apply
        run: |
          DIRS=$(echo "${{ steps.changed-files.outputs.all_modified_files }}" | tr ' ' '\n' | grep 'scripts/tofu/live' | xargs -n1 dirname | sort -u)
          
          for dir in $DIRS; do
            if ls $dir/*.tf 1> /dev/null 2>&1; then
              echo "::group::Applying $dir"
              cd $GITHUB_WORKSPACE/$dir
              tofu init -no-color -input=false
              tofu apply -no-color -input=false -lock-timeout=60m -auto-approve
              echo "::endgroup::"
            else
              echo "No .tf files in $dir, skipping..."
            fi
          done

      - uses: jwalton/gh-find-current-pr@master
        id: find_pr
        with:
          state: all

      - uses: peter-evans/create-or-update-comment@v4
        if: steps.find_pr.outputs.number
        env:
          RESULT_EMOJI: ${{ steps.apply.outcome == 'success' && '✅' || '⚠️' }}
        with:
          issue-number: ${{ steps.find_pr.outputs.number }}
          body: |
            ## ${{ env.RESULT_EMOJI }} Tofu Apply Results
            
            Executed apply on changed modules.
            
            See workflow run for detailed output.
